# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20160627_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 27, 12, 15, 1, 716435, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
